<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Luna BURATTI-FAYOLLE">
    <title>To-do list - JavaScript</title>
    <script type="text/javascript" src="js/app.js" defer></script>
    <link rel="stylesheet" href="css/style.css" type="text/css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" type="text/css" />
    <link rel="icon" type="image/x-icon" href="favicon/favicon-48x48.png" />
</head>
<body>
    <h1><?= __('To-do list JavaScript') ?></h1>
    
    <h2><?= __('Sélectionnez une langue :') ?></h2>
    <div class="dropdown">
        <a href="#"><?= __('Langue')?></a>
        <div class="dropdown-content hide">
            <div><a href="index.php?lang=fr" class="lang-change">Français</a></div>
            <div><a href="index.php?lang=en" class="lang-change">English</a></div>
        </div>
    </div>
    
    <h2><?= __('Vos tâches') ?></h2>
    
    <section id="all-tasks">
        <ul id="list-unstyled"></ul>
    </section>
    
    <section id="task-form" class="section-form">
        <form class="d-flex">
            <fieldset id="create-task-form">
                <legend>
                    <h2><?= __('Créer une nouvelle tâche :') ?></h2>
                </legend>
                    <article class="form-group">
                        <label for="task-name"><?= __('Nom de la tâche :') ?></label>
                        <!--name sera le nom de la tâche, c'est important de le déclarer-->
                        <input type="text" size="45" name="task_name" id="task-name" class="input" placeholder=<?= __('"Ex : Faire les courses"') ?> required />
                    </article>
                    
                    <article class="form-group">
                        <label for="choose-category"><?= __('Catégorie :') ?></label>
                        <select name="choose_category" id="choose-category" class="input">
                            <option value="Sélectionner" disabled><?= __('-- Sélectionner une catégorie --') ?></option>
                            <option value="(Travail)" class="card category"><?= __('Travail') ?></option>
                            <option value="(Etudes)" class="card category"><?= __('Etudes') ?></option>
                            <option value="(Alimentation)" class="card category">Alimentation</option>
                            <option value="(Maison)" class="card category"><?= __('Maison') ?></option>
                            <option value="(Sport)" class="card category">Sport</option>
                            <option value="(Hygiène)" class="card category"><?= __('Hygiène') ?></option>
                            <option value="(Hobbies)" class="card category">Hobbies</option>
                            <option value="(Autre)" class="card category"><?= __('Autre') ?></option>
                            <option value="(Sans catégorie)" class="card category" selected><?= __('Sans catégorie') ?></option>
                        </select>
                    </article>
                    
                    <article class="form-group">
                        <label for="choose-priority"><?= __('Priorité :') ?></label>
                        <select name="choose_priority" id="choose-priority" class="input">
                            <option value="Sélectionner"><?= __('-- Sélectionner une priorité --') ?></option>
                            <option value="1" class="card priority"><?= __('Elevée') ?></option>
                            <option value="2" class="card priority"><?= __('Normale') ?></option>
                            <option value="3" class="card priority"><?= __('Basse') ?></option>
                        </select>
                    </article>
                    
                    <button id="add-btn"><?= __('Ajouter la tâche') ?></button>
            </fieldset>
        </form>
    </section>
        
    <section id="filter-form" class="section-form">
        <form class="d-flex">
            <fieldset>
                <legend><h2><?= __('Filtrer par :') ?></h2></legend>
                    <article class="form-group">
                        <label for="filter-priority"><?= __('Priorité :') ?></label>
                        <select name="filter_priority" id="filter-priority" onchange="priorityType()" class="input">
                            <option value="Sélectionner"><?= __('-- Sélectionner une priorité --') ?></option>
                            <option value="1"><?= __('Elevée') ?></option>
                            <option value="2"><?= __('Normale') ?></option>
                            <option value="3"><?= __('Basse') ?></option>
                            <option value="0"><?= __('Sans priorité') ?></option>
                        </select>
                    </article>
                    
                    <article class="form-group">
                        <label for="filter-category"><?= __('Catégorie :') ?></label>    
                        <select name="filter_category" id="filter-category" onchange="categoryType()" class="input">
                            <option value="Sélectionner" disabled><?= __('-- Sélectionner une catégorie --') ?></option>
                            <option value="Travail"><?= __('Travail') ?></option>
                            <option value="Etudes"><?= __('Etudes') ?></option>
                            <option value="Alimentation">Alimentation</option>
                            <option value="Maison"><?= __('Maison') ?></option>
                            <option value="Sport">Sport</option>
                            <option value="Hygiène"><?= __('Hygiène') ?></option>
                            <option value="Hobbies">Hobbies</option>
                            <option value="Autre"><?= __('Autre') ?></option>
                            <option value="(Sans catégorie)" selected><?= __('Sans catégorie') ?></option>
                        </select>
                    </article>
                    
                    <button id="display-btn"><?= __('Afficher les tâches') ?></button>
            </fieldset>
        </form>
    </section>
    
    <button id="delete-task-btn" class="button"><?= __('Supprimer les tâches terminées') ?></button>
    <button id="delete-all-btn" class="button"><?= __('Supprimer toutes les tâches') ?></button>
    <button id="activate-msg" class="button" disabled><?= __('Réactiver le prompt') ?></button>
</body>
</html>
